# Generated by Django 5.0.6 on 2025-05-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='currency',
            field=models.CharField(choices=[('DT', 'Tunisian Dinar (DT)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'British Pound (£)'), ('¥', 'Japanese Yen (¥)'), ('₹', 'Indian Rupee (₹)'), ('د.إ', 'UAE Dirham (د.إ)'), ('SAR', 'Saudi Riyal (SAR)'), ('MAD', 'Moroccan Dirham (MAD)'), ('DZD', 'Algerian Dinar (DZD)')], default='DT', help_text='Currency symbol to display with all monetary values', max_length=5),
        ),
    ]
