# Generated by Django 5.0.6 on 2024-07-12 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 12, 16, 5, 33, 131991, tzinfo=datetime.timezone.utc)),
        ),
    ]
