# Generated by Django 5.0.6 on 2024-07-22 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 9, 51, 8, 901890, tzinfo=datetime.timezone.utc)),
        ),
    ]
