# Generated by Django 5.0.6 on 2024-09-14 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 8, 3, 2, 379715, tzinfo=datetime.timezone.utc)),
        ),
    ]
