# Generated by Django 5.0.6 on 2024-09-23 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 23, 9, 15, 46, 578810, tzinfo=datetime.timezone.utc)),
        ),
    ]
