# Generated by Django 5.0.6 on 2025-04-26 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 26, 9, 55, 2, 26503, tzinfo=datetime.timezone.utc)),
        ),
    ]
