# Generated by Django 5.0.6 on 2025-04-26 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_financeentry_entry_date_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 26, 10, 43, 54, 226417, tzinfo=datetime.timezone.utc)),
        ),
    ]
