# Generated by Django 5.0.6 on 2025-04-26 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_invoice_alter_financeentry_entry_date_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 26, 18, 41, 25, 999060, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
