# Generated by Django 5.0.6 on 2025-04-26 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_financeentry_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 26, 18, 44, 56, 218034, tzinfo=datetime.timezone.utc)),
        ),
    ]
