# Generated by Django 5.0.6 on 2025-04-26 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 26, 19, 40, 18, 171094, tzinfo=datetime.timezone.utc)),
        ),
    ]
