# Generated by Django 5.0.6 on 2025-04-27 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custom_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual override for invoice total.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 27, 10, 1, 4, 800866, tzinfo=datetime.timezone.utc)),
        ),
    ]
