# Generated by Django 5.0.6 on 2025-05-01 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tva_rate', models.DecimalField(decimal_places=2, default=19.0, help_text='Default TVA (VAT) rate in percentage (e.g., 19.00 for 19%)', max_digits=5)),
                ('stamp_fee', models.DecimalField(decimal_places=2, default=1.0, help_text='Stamp fee amount to be added to all invoices', max_digits=6)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='include_stamp_fee',
            field=models.BooleanField(default=True, help_text='Whether to include the stamp fee in this invoice.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tva_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TVA (VAT) rate in percentage. If left blank, the default site setting will be used.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 1, 11, 16, 34, 210742, tzinfo=datetime.timezone.utc)),
        ),
    ]
