# Generated by Django 5.0.6 on 2025-05-01 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sitesettings_invoice_include_stamp_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 1, 11, 17, 26, 135894, tzinfo=datetime.timezone.utc)),
        ),
    ]
