# Generated by Django 5.0.6 on 2025-05-01 11:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0031_alter_financeentry_entry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AddField(
            model_name='entrycategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_categories', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 1, 11, 38, 20, 86747, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tva_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TVA (VAT) rate in percentage. If left blank, the default company setting will be used.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='entrycategory',
            unique_together={('company', 'category_title')},
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('company', 'name')},
        ),
    ]
