# Generated by Django 5.0.6 on 2025-05-01 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_sitesettings_entrycategory_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 1, 12, 42, 27, 1223, tzinfo=datetime.timezone.utc)),
        ),
    ]
