# Generated by Django 5.0.6 on 2025-05-04 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 10, 11, 55, 72642, tzinfo=datetime.timezone.utc)),
        ),
    ]
