# Generated by Django 5.0.6 on 2025-05-04 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_financeentry_entry_date_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 15, 14, 44, 498346, tzinfo=datetime.timezone.utc)),
        ),
    ]
