# Generated by Django 5.0.6 on 2025-05-06 17:52

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload a receipt or invoice for this expense', null=True, upload_to=core.models.expense_attachment_path),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 6, 17, 52, 8, 116947, tzinfo=datetime.timezone.utc)),
        ),
    ]
