# Generated by Django 5.0.6 on 2025-05-06 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_expense_attachment_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived products are not shown in active lists but remain available for historical invoices'),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 6, 18, 7, 45, 990052, tzinfo=datetime.timezone.utc)),
        ),
    ]
