# Generated by Django 5.0.6 on 2025-05-06 19:45

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the product', null=True, upload_to=core.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 6, 19, 45, 55, 763871, tzinfo=datetime.timezone.utc)),
        ),
    ]
