# Generated by Django 5.0.6 on 2025-05-10 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_product_image_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 10, 9, 34, 27, 362458, tzinfo=datetime.timezone.utc)),
        ),
    ]
