# Generated by Django 5.0.6 on 2025-05-10 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 10, 9, 36, 13, 944181, tzinfo=datetime.timezone.utc)),
        ),
    ]
