# Generated by Django 5.0.6 on 2025-05-11 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 11, 21, 10, 26, 234528, tzinfo=datetime.timezone.utc)),
        ),
    ]
