# Generated by Django 5.0.6 on 2025-05-12 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 12, 21, 23, 19, 183616, tzinfo=datetime.timezone.utc)),
        ),
    ]
