# Generated by Django 5.0.6 on 2025-05-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_financeentry_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeentry',
            name='entry_category',
        ),
        migrations.RemoveField(
            model_name='financeentry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='financeentry',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='EntryCategory',
        ),
        migrations.DeleteModel(
            name='FinanceEntry',
        ),
    ]
