# Generated by Django 5.0.6 on 2025-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='TVA rate in percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price without TVA', max_digits=10),
        ),
    ]
