# Generated by Django 5.0.6 on 2025-06-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_product_tva_rate_alter_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_with_tva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price including TVA', max_digits=10),
        ),
    ]
